/**
 * Skill Bridge — Educator & Education Program Catalog
 * Curated catalog of educational providers and structured learning programs.
 * Explicitly marks sample/test providers vs external open opportunities.
 * No false commercial partnerships or fabricated credentials.
 */

import { Educator, EducationProgram } from "./types";

export const SAMPLE_EDUCATORS: Educator[] = [
  {
    id: "edu-openssf",
    name: "Open Source Security Foundation (OpenSSF)",
    slug: "openssf",
    description:
      "Cross-industry foundation dedicated to securing open source software, software supply chains, and developer security education.",
    website: "https://openssf.org",
    verifiedStatus: "external_opportunity",
    statusLabel: "External Learning Opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-owasp",
    name: "OWASP Foundation Educational Resources",
    slug: "owasp",
    description:
      "Global nonprofit organization focused on improving the security of software applications, API security standards, and threat modeling.",
    website: "https://owasp.org",
    verifiedStatus: "external_opportunity",
    statusLabel: "External Learning Opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-cncf",
    name: "Cloud Native Computing Foundation (CNCF)",
    slug: "cncf",
    description:
      "Hub for open source cloud-native technology education, Kubernetes ecosystem architectures, and microservices observability.",
    website: "https://www.cncf.io/training",
    verifiedStatus: "external_opportunity",
    statusLabel: "External Learning Opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-linux-foundation",
    name: "Linux Foundation Training & Education",
    slug: "linux-foundation",
    description:
      "World-class vendor-neutral open technology curricula covering systems development, cloud infrastructure, and DevOps practices.",
    website: "https://training.linuxfoundation.org",
    verifiedStatus: "external_opportunity",
    statusLabel: "External Learning Opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-deeplearning",
    name: "Open Machine Learning & Deep Learning Initiative",
    slug: "deeplearning-open",
    description:
      "Curated open educational pathway for foundational machine learning, large language models, and practical AI system evaluation.",
    website: "https://www.deeplearning.ai",
    verifiedStatus: "external_opportunity",
    statusLabel: "External Learning Opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-skillbridge-labs",
    name: "Skill Bridge Open Labs (Sample Provider)",
    slug: "skillbridge-labs",
    description:
      "Internal development lab providing practical interactive coding exercises and mock challenge scenarios for student evaluation.",
    website: "https://github.com/skillbridge",
    verifiedStatus: "sample_provider",
    statusLabel: "Sample Learning Provider",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
];

export const SAMPLE_EDUCATION_PROGRAMS: EducationProgram[] = [
  // ==========================================================================
  // CYBERSECURITY PROGRAMS
  // ==========================================================================
  {
    id: "prog-sec-appsec-fundamentals",
    educatorId: "edu-owasp",
    educatorName: "OWASP Foundation Educational Resources",
    title: "OWASP Application Security & Secure Coding Foundations",
    description:
      "Deep dive into input sanitization, mitigation of OWASP Top 10 vulnerabilities, secure session tokens, and cryptographic identity storage.",
    programUrl: "https://owasp.org/www-project-top-ten/",
    domains: ["security"],
    niches: ["app-sec", "soc-threat"],
    skillIds: [
      "auth-identity",
      "web-security",
      "secure-coding",
      "api-security",
      "vuln-assessment",
    ],
    difficulty: "beginner",
    deliveryType: "Online Self-Paced",
    duration: "4 Weeks (4–6 hrs/wk)",
    certification: "Certificate of Completion",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-sec-openssf-dev",
    educatorId: "edu-openssf",
    educatorName: "Open Source Security Foundation (OpenSSF)",
    title: "Developing Secure Software & Supply Chain Hardening (LFD121)",
    description:
      "Comprehensive training on secure software design principles, input validation, avoiding buffer overflows and injection, and dependency auditing.",
    programUrl: "https://openssf.org/training/courses/",
    domains: ["security", "software"],
    niches: ["app-sec", "cloud-sec", "clean-code"],
    skillIds: [
      "secure-coding",
      "auth-identity",
      "crypto-foundations",
      "code-smell-elimination",
      "infra-as-code-sec",
    ],
    difficulty: "intermediate",
    deliveryType: "Online Self-Paced",
    duration: "6 Weeks (5 hrs/wk)",
    certification: "OpenSSF Verified Digital Badge",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-sec-soc-defense",
    educatorId: "edu-skillbridge-labs",
    educatorName: "Skill Bridge Open Labs (Sample Provider)",
    title: "SOC Analyst Practical Incident Response & SIEM Analysis Lab",
    description:
      "Hands-on interactive lab analyzing telemetry logs, configuring detection alert rules, triaging malware alerts, and generating incident reports.",
    programUrl: "https://github.com/skillbridge/soc-incident-lab",
    domains: ["security"],
    niches: ["soc-threat", "app-sec"],
    skillIds: [
      "siem-telemetry",
      "incident-response",
      "network-forensics",
      "threat-intel",
      "log-investigation",
      "malware-triage",
    ],
    difficulty: "intermediate",
    deliveryType: "Hands-on Lab",
    duration: "3 Weeks (8 hrs/wk)",
    certification: "Practical Lab Completion Record",
    verifiedStatus: "sample_provider",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-sec-cloud-zero-trust",
    educatorId: "edu-cncf",
    educatorName: "Cloud Native Computing Foundation (CNCF)",
    title: "Cloud Native Security & Kubernetes Cluster Hardening",
    description:
      "Master Kubernetes RBAC policies, container image signing, Pod security standards, zero-trust network policies, and runtime threat detection.",
    programUrl: "https://www.cncf.io/training/certification/cks/",
    domains: ["security", "cloud"],
    niches: ["cloud-sec", "k8s-platform", "cloud-infra"],
    skillIds: [
      "cloud-iam",
      "k8s-hardening",
      "cwpp-cspm",
      "infra-as-code-sec",
      "zero-trust-arch",
      "k8s-pod-orchestration",
    ],
    difficulty: "advanced",
    deliveryType: "Hands-on Lab",
    duration: "8 Weeks (6 hrs/wk)",
    certification: "CKS Preparation Syllabus Certificate",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-sec-pentest-methodology",
    educatorId: "edu-skillbridge-labs",
    educatorName: "Skill Bridge Open Labs (Sample Provider)",
    title: "Offensive Security & Ethical Penetration Testing Track",
    description:
      "Step-by-step methodologies for network port scanning, service enumeration, Active Directory privilege escalation, and formal vulnerability disclosure.",
    programUrl: "https://github.com/skillbridge/pentest-foundations",
    domains: ["security"],
    niches: ["pentest-red", "app-sec"],
    skillIds: [
      "port-scanning",
      "privilege-escalation",
      "wireless-attacks",
      "ad-exploitation",
      "metasploit-foundations",
      "report-generation",
      "vuln-assessment",
    ],
    difficulty: "intermediate",
    deliveryType: "Hands-on Lab",
    duration: "5 Weeks (6 hrs/wk)",
    certification: "Red Team Lab Challenge Badge",
    verifiedStatus: "sample_provider",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },

  // ==========================================================================
  // AI & MACHINE LEARNING PROGRAMS
  // ==========================================================================
  {
    id: "prog-aiml-applied-foundations",
    educatorId: "edu-deeplearning",
    educatorName: "Open Machine Learning & Deep Learning Initiative",
    title: "Machine Learning Foundations & Supervised Algorithms",
    description:
      "Mathematical intuition and Python implementation of linear/logistic regression, decision trees, cross-validation metrics, and feature engineering.",
    programUrl: "https://www.deeplearning.ai/courses/machine-learning-specialization/",
    domains: ["ai-ml"],
    niches: ["applied-ml", "edge-ai"],
    skillIds: [
      "supervised-learning",
      "feature-engineering",
      "model-evaluation",
      "data-preprocessing",
      "deep-learning-foundations",
      "mlops-tracking",
    ],
    difficulty: "beginner",
    deliveryType: "Online Self-Paced",
    duration: "6 Weeks (5 hrs/wk)",
    certification: "Specialization Certificate",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-aiml-llm-rag-engineering",
    educatorId: "edu-deeplearning",
    educatorName: "Open Machine Learning & Deep Learning Initiative",
    title: "Generative AI Systems & Vector RAG Architectures",
    description:
      "Building production LLM applications: vector embeddings, chunking strategies, dense retrieval, prompt chaining, and evaluation harnesses.",
    programUrl: "https://www.deeplearning.ai/short-courses/",
    domains: ["ai-ml"],
    niches: ["gen-ai-nlp", "applied-ml"],
    skillIds: [
      "transformer-arch",
      "text-embeddings",
      "fine-tuning-peft",
      "tokenization-vocab",
      "rag-pipelines",
      "hallucination-mitigation",
    ],
    difficulty: "intermediate",
    deliveryType: "Interactive Cohort",
    duration: "4 Weeks (6 hrs/wk)",
    certification: "Generative AI Practitioner Badge",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-aiml-cv-deep-learning",
    educatorId: "edu-skillbridge-labs",
    educatorName: "Skill Bridge Open Labs (Sample Provider)",
    title: "Computer Vision with PyTorch: From CNNs to Segmentation",
    description:
      "Practical computer vision pipelines covering convolutional networks, YOLO object detection, transfer learning, and latency optimization.",
    programUrl: "https://github.com/skillbridge/computer-vision-pytorch",
    domains: ["ai-ml"],
    niches: ["cv-imaging", "applied-ml", "edge-ai"],
    skillIds: [
      "cnn-architectures",
      "object-detection",
      "image-segmentation",
      "image-augmentation",
      "transfer-learning-vision",
      "inference-acceleration",
    ],
    difficulty: "intermediate",
    deliveryType: "Hands-on Lab",
    duration: "5 Weeks (5 hrs/wk)",
    certification: "Vision Lab Completion Certificate",
    verifiedStatus: "sample_provider",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-aiml-edge-inference",
    educatorId: "edu-linux-foundation",
    educatorName: "Linux Foundation Training & Education",
    title: "Edge AI & Low-Power Neural Network Optimization",
    description:
      "Deploy deep learning models on constrained hardware using ONNX runtimes, post-training INT8 quantization, and hardware acceleration.",
    programUrl: "https://training.linuxfoundation.org/training/ai-edge/",
    domains: ["ai-ml"],
    niches: ["edge-ai", "applied-ml"],
    skillIds: [
      "model-quantization",
      "onnx-runtimes",
      "tensorrt-optimization",
      "edge-tpu-deployment",
      "latency-profiling",
      "pruning-sparsity",
    ],
    difficulty: "advanced",
    deliveryType: "Online Self-Paced",
    duration: "6 Weeks (4 hrs/wk)",
    certification: "Edge Systems Specialist Certificate",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },

  // ==========================================================================
  // CLOUD & INFRASTRUCTURE PROGRAMS
  // ==========================================================================
  {
    id: "prog-cloud-k8s-core",
    educatorId: "edu-cncf",
    educatorName: "Cloud Native Computing Foundation (CNCF)",
    title: "Kubernetes Administration & Cloud Native Architecture",
    description:
      "Core Kubernetes constructs: pods, deployments, statefulsets, cluster networking, Helm chart authoring, and declarative GitOps pipelines.",
    programUrl: "https://www.cncf.io/training/certification/cka/",
    domains: ["cloud"],
    niches: ["k8s-platform", "cloud-infra", "sre-ops"],
    skillIds: [
      "k8s-pod-orchestration",
      "ingress-networking",
      "helm-packaging",
      "service-mesh",
      "container-cgroups",
      "gitops-argocd",
    ],
    difficulty: "intermediate",
    deliveryType: "Hands-on Lab",
    duration: "8 Weeks (6 hrs/wk)",
    certification: "CKA Aligned Curriculum Certificate",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-cloud-iac-terraform",
    educatorId: "edu-linux-foundation",
    educatorName: "Linux Foundation Training & Education",
    title: "Infrastructure as Code with Terraform & Multi-Cloud CI/CD",
    description:
      "Modular cloud architecture with Terraform, remote state locking, drift detection, immutable server images, and automated compliance policies.",
    programUrl: "https://training.linuxfoundation.org/training/terraform-infrastructure/",
    domains: ["cloud"],
    niches: ["cloud-infra", "hybrid-multi", "sre-ops"],
    skillIds: [
      "terraform-state",
      "hcl-modularization",
      "ansible-automation",
      "immutable-infrastructure",
      "drift-detection",
      "cloudformation-foundations",
    ],
    difficulty: "beginner",
    deliveryType: "Online Self-Paced",
    duration: "4 Weeks (5 hrs/wk)",
    certification: "Certificate of Achievement",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-cloud-sre-observability",
    educatorId: "edu-skillbridge-labs",
    educatorName: "Skill Bridge Open Labs (Sample Provider)",
    title: "Site Reliability Engineering (SRE) & Observability Masterclass",
    description:
      "Prometheus metrics instrumentation, Grafana dashboard creation, distributed trace propagation with OpenTelemetry, and error budget calculation.",
    programUrl: "https://github.com/skillbridge/sre-observability-course",
    domains: ["cloud", "software"],
    niches: ["sre-ops", "api-backend", "k8s-platform"],
    skillIds: [
      "distributed-tracing",
      "prometheus-alerting",
      "grafana-dashboarding",
      "chaos-engineering",
      "slo-sli-budgeting",
      "root-cause-analysis",
    ],
    difficulty: "intermediate",
    deliveryType: "Interactive Cohort",
    duration: "5 Weeks (4 hrs/wk)",
    certification: "SRE Foundations Badge",
    verifiedStatus: "sample_provider",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },

  // ==========================================================================
  // WEB & FRONTEND PROGRAMS
  // ==========================================================================
  {
    id: "prog-web-modern-frontend",
    educatorId: "edu-skillbridge-labs",
    educatorName: "Skill Bridge Open Labs (Sample Provider)",
    title: "Modern React Architecture & Component Systems",
    description:
      "Build production-grade applications using React Server Components, state machines, accessible WAI-ARIA widgets, and responsive tokenized styling.",
    programUrl: "https://github.com/skillbridge/modern-frontend-curriculum",
    domains: ["web"],
    niches: ["frontend-arch", "web-perf"],
    skillIds: [
      "react-server-components",
      "state-machines",
      "hydration-tuning",
      "accessible-ui-wai-aria",
      "tailwind-design-tokens",
      "nextjs-app-router",
    ],
    difficulty: "intermediate",
    deliveryType: "Hands-on Lab",
    duration: "6 Weeks (5 hrs/wk)",
    certification: "Frontend Architecture Certificate",
    verifiedStatus: "sample_provider",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-web-api-backend",
    educatorId: "edu-owasp",
    educatorName: "OWASP Foundation Educational Resources",
    title: "High-Performance REST & GraphQL API Engineering",
    description:
      "Design resilient backend web APIs: database indexing, connection pooling, Redis distributed caching, rate-limiting, and schema validation.",
    programUrl: "https://owasp.org/www-project-api-security/",
    domains: ["web", "software"],
    niches: ["backend-services", "api-backend", "distributed-web"],
    skillIds: [
      "rest-api-design",
      "relational-indexing",
      "distributed-caching",
      "async-queues",
      "database-migrations",
      "api-rate-limiting",
      "api-security",
    ],
    difficulty: "intermediate",
    deliveryType: "Online Self-Paced",
    duration: "5 Weeks (6 hrs/wk)",
    certification: "API Systems Specialist Certificate",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-web-perf-core-vitals",
    educatorId: "edu-skillbridge-labs",
    educatorName: "Skill Bridge Open Labs (Sample Provider)",
    title: "Web Performance Engineering & Core Web Vitals Optimization",
    description:
      "Diagnose and optimize Largest Contentful Paint (LCP), Interaction to Next Paint (INP), JavaScript bundle splitting, and browser cache strategies.",
    programUrl: "https://github.com/skillbridge/web-performance-lab",
    domains: ["web"],
    niches: ["web-perf", "frontend-arch"],
    skillIds: [
      "interaction-to-next-paint",
      "largest-contentful-paint",
      "dom-size-reduction",
      "tree-shaking-bundling",
      "browser-cache-strategies",
      "memory-leak-profiling",
    ],
    difficulty: "advanced",
    deliveryType: "Online Self-Paced",
    duration: "3 Weeks (4 hrs/wk)",
    certification: "Performance Optimization Lab Badge",
    verifiedStatus: "sample_provider",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },

  // ==========================================================================
  // SOFTWARE & SYSTEM ARCHITECTURE PROGRAMS
  // ==========================================================================
  {
    id: "prog-soft-clean-code-refactoring",
    educatorId: "edu-linux-foundation",
    educatorName: "Linux Foundation Training & Education",
    title: "Clean Code Engineering, SOLID Principles & Refactoring Patterns",
    description:
      "Transform legacy software into maintainable architectures. Eliminate code smells, minimize cyclomatic complexity, and adhere to SOLID principles.",
    programUrl: "https://training.linuxfoundation.org/training/clean-code-practices/",
    domains: ["software"],
    niches: ["clean-code", "sys-arch", "test-eng"],
    skillIds: [
      "cyclomatic-complexity",
      "extract-method-refactoring",
      "antipattern-detection",
      "dry-solid-adherence",
      "legacy-characterization-tests",
      "code-smell-elimination",
    ],
    difficulty: "beginner",
    deliveryType: "Online Self-Paced",
    duration: "4 Weeks (4 hrs/wk)",
    certification: "Clean Code Practitioner Certificate",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-soft-tdd-test-automation",
    educatorId: "edu-skillbridge-labs",
    educatorName: "Skill Bridge Open Labs (Sample Provider)",
    title: "Test-Driven Development (TDD) & Automated Testing Pipelines",
    description:
      "Master unit test isolation, mocking strategies, contract testing with Pact, and mutation testing to eliminate subtle software regressions.",
    programUrl: "https://github.com/skillbridge/tdd-test-automation",
    domains: ["software", "web"],
    niches: ["test-eng", "clean-code", "backend-services"],
    skillIds: [
      "unit-test-isolation",
      "mocking-stubbing",
      "test-driven-development",
      "mutation-testing",
      "contract-testing-pact",
      "code-coverage-analysis",
    ],
    difficulty: "intermediate",
    deliveryType: "Hands-on Lab",
    duration: "4 Weeks (6 hrs/wk)",
    certification: "Test Engineering Certificate",
    verifiedStatus: "sample_provider",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-soft-distributed-systems",
    educatorId: "edu-linux-foundation",
    educatorName: "Linux Foundation Training & Education",
    title: "Distributed Systems Architecture & Resilient Microservices",
    description:
      "Domain-Driven Design (DDD), hexagonal architectures, event sourcing, distributed consensus mechanisms, and fault-tolerant communication.",
    programUrl: "https://training.linuxfoundation.org/training/distributed-systems-design/",
    domains: ["software", "cloud"],
    niches: ["sys-arch", "distributed-web", "cloud-infra"],
    skillIds: [
      "microservices-boundaries",
      "domain-driven-design",
      "hexagonal-architecture",
      "api-versioning-contracts",
      "cqrs-event-sourcing",
      "distributed-consensus",
      "distributed-tracing",
    ],
    difficulty: "advanced",
    deliveryType: "Interactive Cohort",
    duration: "8 Weeks (6 hrs/wk)",
    certification: "Advanced Systems Architect Certificate",
    verifiedStatus: "external_opportunity",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
];

/**
 * Helper to retrieve all active educators
 */
export function getActiveEducators(): Educator[] {
  return SAMPLE_EDUCATORS.filter((e) => e.active);
}

/**
 * Helper to retrieve all active education programs
 */
export function getActivePrograms(): EducationProgram[] {
  return SAMPLE_EDUCATION_PROGRAMS.filter((p) => p.active);
}
