/**
 * Skill Bridge — AYUSH Apex Educator & Program Catalog
 * Curated accredited institutions under Ministry of Ayush.
 * Strictly scoped to the 5 canonical AYUSH systems.
 */

import { Educator, EducationProgram } from "./types";

export const SAMPLE_EDUCATORS: Educator[] = [
  {
    id: "edu-aiia",
    name: "All India Institute of Ayurveda (AIIA)",
    slug: "aiia-new-delhi",
    description: "Apex autonomous institute under Ministry of Ayush establishing tertiary healthcare standards, clinical trials, and postgraduate Ayurveda education.",
    website: "https://aiia.gov.in",
    verifiedStatus: "verified_partner",
    statusLabel: "National Apex Institute",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-nia",
    name: "National Institute of Ayurveda (NIA)",
    slug: "nia-jaipur",
    description: "Deemed to be University under De-novo Category, premier center for classical Ayurvedic education, pharmacopoeial standardization, and drug research.",
    website: "https://nia.nic.in",
    verifiedStatus: "verified_partner",
    statusLabel: "National Apex Institute",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-nin",
    name: "National Institute of Naturopathy (NIN)",
    slug: "nin-pune",
    description: "Autonomous body under Ministry of Ayush, leader in clinical naturopathy, hydrotherapy protocols, fasting biology, and lifestyle disorder management.",
    website: "https://punenin.org",
    verifiedStatus: "verified_partner",
    statusLabel: "National Apex Institute",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-nium",
    name: "National Institute of Unani Medicine (NIUM)",
    slug: "nium-bangalore",
    description: "Premier academic and clinical research institute for Unani Medicine, specializing in Ilaj-bit-Tadbeer regimental therapies and classical formulation standardization.",
    website: "https://nium.in",
    verifiedStatus: "verified_partner",
    statusLabel: "National Apex Institute",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-nis",
    name: "National Institute of Siddha (NIS)",
    slug: "nis-chennai",
    description: "Center of excellence for Siddha medicine, Gunapaadam herbal-mineral pharmacology, and Varmam physical therapy research.",
    website: "https://nischennai.org",
    verifiedStatus: "verified_partner",
    statusLabel: "National Apex Institute",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-nih",
    name: "National Institute of Homoeopathy (NIH)",
    slug: "nih-kolkata",
    description: "Apex national institute for tertiary Homoeopathic medical education, repertorial clinical research, and drug proving documentation.",
    website: "https://nih.nic.in",
    verifiedStatus: "verified_partner",
    statusLabel: "National Apex Institute",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-mdniy",
    name: "Morarji Desai National Institute of Yoga (MDNIY)",
    slug: "mdniy-delhi",
    description: "Focal center for Yoga education, scientific research in Yogic physiology, and national accreditation under Yoga Certification Board (YCB).",
    website: "https://yogamdniy.nic.in",
    verifiedStatus: "verified_partner",
    statusLabel: "National Apex Institute",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "edu-ccras",
    name: "Central Council for Research in Ayurvedic Sciences (CCRAS)",
    slug: "ccras-delhi",
    description: "Autonomous research organization coordinating formulation research, botanical authentication, and multi-center evidence trials in Ayurveda.",
    website: "https://ccras.nic.in",
    verifiedStatus: "verified_partner",
    statusLabel: "Apex Research Council",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
];

export const SAMPLE_EDUCATION_PROGRAMS: EducationProgram[] = [
  {
    id: "prog-panchakarma-specialist",
    educatorId: "edu-aiia",
    educatorName: "All India Institute of Ayurveda (AIIA)",
    title: "Clinical Fellowship in Advanced Panchakarma Protocol Execution",
    description: "Comprehensive hospital clinical immersion covering Snehapana dosage escalation, Kostha evaluation, Samyak Snigdha monitoring, and multi-day Samsarjana Krama recovery.",
    programUrl: "https://aiia.gov.in/fellowship/panchakarma",
    domains: ["ayurveda"],
    niches: ["panchakarma", "kayachikitsa"],
    skillIds: [
      "snehana-swedana",
      "basti-therapy",
      "virechana-vamana",
      "samsarjana-krama",
      "panchakarma-dosha-monitoring",
    ],
    difficulty: "advanced",
    deliveryType: "Hands-on Lab",
    duration: "12 Weeks (15 hrs/wk)",
    certification: "AIIA Verified Clinical Completion Certificate",
    verifiedStatus: "verified_partner",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-dravyaguna-standardization",
    educatorId: "edu-nia",
    educatorName: "National Institute of Ayurveda (NIA)",
    title: "Ayurvedic Pharmacopoeia Standards & HPTLC Botanical Assay",
    description: "Laboratory and field training on macro/microscopic raw drug authentication, Ayurvedic Pharmacopoeia of India monograph verification, and phytochemical profiling.",
    programUrl: "https://nia.nic.in/programs/pharmacognosy-standards",
    domains: ["ayurveda"],
    niches: ["dravyaguna", "rasashastra"],
    skillIds: [
      "botanical-authentication",
      "phytochemical-hptlc",
      "api-monograph-verification",
      "rasashastra-sodhana",
      "bhasma-pariksha",
    ],
    difficulty: "intermediate",
    deliveryType: "Interactive Cohort",
    duration: "8 Weeks (8 hrs/wk)",
    certification: "NIA Advanced Analytical Pharmacognosy Certificate",
    verifiedStatus: "verified_partner",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-yoga-therapy-clinical",
    educatorId: "edu-mdniy",
    educatorName: "Morarji Desai National Institute of Yoga (MDNIY)",
    title: "Therapeutic Yoga Chikitsa for Metabolic & Musculoskeletal Disorders",
    description: "Evidence-based clinical yoga protocol design, disease-specific asana modification, therapeutic pranayama biomechanics, and autonomic nervous system regulation.",
    programUrl: "https://yogamdniy.nic.in/education/clinical-yoga-therapy",
    domains: ["yoga-naturopathy"],
    niches: ["yoga-therapy", "pranayama-science"],
    skillIds: [
      "asana-biomechanics",
      "therapeutic-pranayama",
      "shatkarma-cleansing",
      "stress-autonomic-regulation",
      "ycb-clinical-alignment",
    ],
    difficulty: "intermediate",
    deliveryType: "Interactive Cohort",
    duration: "10 Weeks (10 hrs/wk)",
    certification: "MDNIY Level 3 Clinical Yoga Therapist Credential",
    verifiedStatus: "verified_partner",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-naturopathy-lifestyle",
    educatorId: "edu-nin",
    educatorName: "National Institute of Naturopathy (NIN)",
    title: "Clinical Hydrotherapy, Mud Protocols & Fasting Biochemistry",
    description: "Intensive hospital clinical practicum in temperature-graded hydrotherapy, gastrointestinal mud packs, controlled clinical fasting monitoring, and alkaline dietetics.",
    programUrl: "https://punenin.org/fellowship/naturopathic-medicine",
    domains: ["yoga-naturopathy"],
    niches: ["naturopathic-medicine", "diet-nutrition"],
    skillIds: [
      "clinical-hydrotherapy",
      "mud-application-protocols",
      "fasting-biochemistry-monitoring",
      "naturopathic-dietetics",
      "vitality-assessment",
    ],
    difficulty: "advanced",
    deliveryType: "Hands-on Lab",
    duration: "8 Weeks (12 hrs/wk)",
    certification: "NIN Clinical Naturopathy Practitioner Credential",
    verifiedStatus: "verified_partner",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-unani-regimental",
    educatorId: "edu-nium",
    educatorName: "National Institute of Unani Medicine (NIUM)",
    title: "Ilaj-bit-Tadbeer (Regimental Therapy) & Hijama Cupping Specialization",
    description: "Practical operating room mastery of dry and wet cupping (Hijama), Fasd (venesection), Dalk (massage therapy), and Mizaj temperament profiling in chronic inflammation.",
    programUrl: "https://nium.in/programs/regimental-therapies",
    domains: ["unani"],
    niches: ["ilaj-bit-tadbeer", "mizaj-assessment"],
    skillIds: [
      "hijama-cupping-technique",
      "fasd-venesection-protocols",
      "dalk-therapeutic-massage",
      "mizaj-constitution-typing",
      "unani-formulation-qarabadeen",
    ],
    difficulty: "intermediate",
    deliveryType: "Hands-on Lab",
    duration: "6 Weeks (8 hrs/wk)",
    certification: "NIUM Certified Regimental Therapist Award",
    verifiedStatus: "verified_partner",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-siddha-varmam",
    educatorId: "edu-nis",
    educatorName: "National Institute of Siddha (NIS)",
    title: "Varmam Anatomical Points, Physical Manipulation & Emergency Traumatology",
    description: "Mastery of 108 vital Varmam energy junctions, physical resuscitation techniques, trauma relief maneuvers, and Thokkanam therapeutic massage integration.",
    programUrl: "https://nischennai.org/courses/varmam-therapy",
    domains: ["siddha"],
    niches: ["varmam-therapy", "gunapaadam"],
    skillIds: [
      "varmam-point-identification",
      "varmam-stimulation-pressure",
      "thokkanam-physical-therapy",
      "siddha-mineral-parpam-chekku",
      "naadi-siddha-diagnostics",
    ],
    difficulty: "advanced",
    deliveryType: "Hands-on Lab",
    duration: "8 Weeks (10 hrs/wk)",
    certification: "NIS Certified Varmam Specialist Credential",
    verifiedStatus: "verified_partner",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "prog-homoeo-repertory",
    educatorId: "edu-nih",
    educatorName: "National Institute of Homoeopathy (NIH)",
    title: "Advanced Computerized Repertorization & Chronic Miasmatic Analysis",
    description: "Deep clinical immersion in Kent and Boenninghausen repertorization hierarchies, radar synthesis algorithms, single-remedy posology selection, and chronic miasm tracking.",
    programUrl: "https://nih.nic.in/programs/advanced-repertory-mastery",
    domains: ["homoeopathy"],
    niches: ["repertorization", "organon-philosophy"],
    skillIds: [
      "computerized-repertory-synthesis",
      "miasmatic-diagnosis-psora-sycosis",
      "organon-posology-50millesimal",
      "materia-medica-comparative",
      "clinical-case-defense",
    ],
    difficulty: "advanced",
    deliveryType: "Online Self-Paced",
    duration: "8 Weeks (6 hrs/wk)",
    certification: "NIH Advanced Repertorial Clinician Certificate",
    verifiedStatus: "verified_partner",
    active: true,
    createdAt: "2026-01-15T00:00:00.000Z",
    updatedAt: "2026-03-01T00:00:00.000Z",
  },
];

export function getProgramsBySkill(skillId: string): EducationProgram[] {
  return SAMPLE_EDUCATION_PROGRAMS.filter(
    (p) => p.active && p.skillIds.includes(skillId)
  );
}

export function getProgramsByDomain(domainId: string): EducationProgram[] {
  return SAMPLE_EDUCATION_PROGRAMS.filter(
    (p) => p.active && p.domains.includes(domainId)
  );
}

export function getProgramsByNiche(nicheId: string): EducationProgram[] {
  return SAMPLE_EDUCATION_PROGRAMS.filter(
    (p) => p.active && p.niches.includes(nicheId)
  );
}

export function getActiveEducators(): Educator[] {
  return SAMPLE_EDUCATORS.filter((e) => e.active);
}

export function getActivePrograms(): EducationProgram[] {
  return SAMPLE_EDUCATION_PROGRAMS.filter((p) => p.active);
}
