-- Skill-Bridge AYUSH Development Interventions Seed (Step 8)
-- Idempotent upsert of curated AYUSH Development Interventions

INSERT INTO public.ayush_development_interventions (
  id,
  title,
  description,
  type,
  competency_id,
  target_maturity,
  estimated_duration,
  difficulty,
  provider,
  evidence_required,
  supporting_resources,
  active
) VALUES
(
  'int-gcp-workshop',
  'ICMR-CDSCO Good Clinical Practice (GCP) for AYUSH Investigators',
  'Comprehensive interactive workshop covering ICMR ethical guidelines, CDSCO clinical trial rules, investigator responsibilities, informed consent, and adverse event reporting tailored for AYUSH clinical interventions.',
  'Workshop',
  'comp-ayush-gcp',
  'Advanced',
  '3 Days (18 Hours)',
  'Advanced',
  'All India Institute of Ayurveda (AIIA) & ICMR Clinical Cell',
  'GCP Investigator Certification and Simulated Ethics Protocol Submission',
  '[{"title": "ICMR Ethical Guidelines 2017", "url": "https://ethics.ncdirindia.org", "type": "document"}]'::jsonb,
  true
),
(
  'int-trial-design-challenge',
  'Whole-System AYUSH Randomized Controlled Trial Protocol Design',
  'Research design challenge adapting whole-system Ayurvedic/Siddha multimodal interventions to pragmatic RCT and adaptive trial designs without compromising classical treatment integrity.',
  'Research Challenge',
  'comp-ayush-trial-design',
  'Advanced',
  '2 Weeks',
  'Advanced',
  'CCRAS Central Research Directorate',
  'Complete SPIRIT-AYUSH compliant Protocol Document & Randomization Plan',
  '[{"title": "SPIRIT Guidelines Extension for Traditional Medicine", "url": "https://www.spirit-statement.org", "type": "document"}]'::jsonb,
  true
),
(
  'int-crf-edc-practical',
  'Electronic Data Capture (EDC) & e-CRF Workflows in AYUSH Trials',
  'Hands-on practical workstation for case report form design, GCP-compliant source data verification, and query resolution in multi-center clinical trials.',
  'Practical Task',
  'comp-ayush-crf-edc',
  'Foundation',
  '1 Week (10 Hours)',
  'Beginner',
  'SkillBridge Clinical Informatics Lab',
  'Validated RedCap/e-CRF Entry Audit Log & Query Resolution Verification',
  '[{"title": "CDISC Clinical Data Standards Overview", "url": "https://www.cdisc.org", "type": "document"}]'::jsonb,
  true
),
(
  'int-literature-evidence-course',
  'Classical Literature Retrieval & PRISMA Systematic Evidence Synthesis',
  'Guided module on extracting Samhita evidence, Sanskrit technical terminology translation, and mapping traditional indications to modern MeSH headings for systematic reviews.',
  'Course',
  'comp-ayush-literature-evidence',
  'Foundation',
  '10 Days',
  'Beginner',
  'National Institute of Ayurveda (NIA) Evidence Cell',
  'PRISMA-AYUSH Systematic Literature Matrix & Evidence Summary',
  '[{"title": "DHARA Digital Helpline for Ayurveda Research Articles", "url": "https://www.dharaonline.org", "type": "document"}]'::jsonb,
  true
),
(
  'int-ethics-icmr-mentor',
  'Institutional Ethics Committee (IEC) Dossier Preparation & Defense',
  'One-on-one and small cohort mentor sessions reviewing informed consent documentation in local vernacular, vulnerable participant safeguards, and risk-benefit justification.',
  'Mentor Session',
  'comp-ayush-ethics-icmr',
  'Applied',
  '4 Sessions (8 Hours)',
  'Intermediate',
  'Apex AYUSH Bioethics Mentorship Forum',
  'IEC Submission Package with Participant Informed Consent in Vernacular',
  '[{"title": "ICMR Guidelines for Biomedical Research in Children and Vulnerable Groups", "url": "https://main.icmr.nic.in", "type": "document"}]'::jsonb,
  true
),
(
  'int-pvpi-adr-assessment',
  'Pharmacovigilance for ASU Drugs & Causality Assessment',
  'Standardized practical assessment evaluating candidate competency in suspected adverse reaction triage, blue form submission, and WHO-UMC causality classification.',
  'Assessment',
  'comp-ayush-pharmacovigilance',
  'Applied',
  '1 Week',
  'Intermediate',
  'National Pharmacovigilance Centre for AYUSH (NPvC)',
  'WHO-UMC Causality Assessment of 3 Standardized Herbal ADR Case Reports',
  '[{"title": "PvPI Blue Form and AYUSH Guidelines", "url": "https://ipc.gov.in", "type": "document"}]'::jsonb,
  true
),
(
  'int-bedside-diagnostics-task',
  'Clinical Nadi Pariksha & Rogi-Roga Assessment at Bedside',
  'Supervised bedside diagnostic task recording pulse patterns (Gati, Vega, Tala), tongue signs (Jihva Pariksha), and Prakriti-Vikriti discordance in real patients.',
  'Practical Task',
  'comp-ayush-bedside-diagnostics',
  'Applied',
  '2 Weeks',
  'Intermediate',
  'Department of Kayachikitsa, AIIA',
  'Clinical Case Diary of 5 Verified Comprehensive Ashta-vidha Pariksha Logsheets',
  '[{"title": "Clinical Methods in Ayurvedic Medicine", "url": "https://aiia.gov.in", "type": "document"}]'::jsonb,
  true
),
(
  'int-panchakarma-workshop',
  'Standardized Purvakarma & Paschatkarma Clinical Supervision',
  'Hands-on clinical workshop covering Snehana-Swedana titration, Vamana/Virechana administration protocols, and complication management in clinical setups.',
  'Workshop',
  'comp-ayush-panchakarma-chikitsa',
  'Applied',
  '5 Days (30 Hours)',
  'Intermediate',
  'National Ayurveda Research Institute for Panchakarma (NARIP)',
  'Clinical Procedure Log and Emergency Protocol Sign-off',
  '[{"title": "Standard Treatment Guidelines for Panchakarma", "url": "https://ccras.nic.in", "type": "document"}]'::jsonb,
  true
),
(
  'int-chronic-mgmt-project',
  'Integrative Metabolic Syndrome & Chronic Care Management Project',
  'Multi-week clinical project assessing longitudinal outcomes, dietetics (Pathya-Apathya), and herbal adjuvant therapies in type-2 diabetes and dyslipidemia.',
  'Industry Project',
  'comp-ayush-chronic-case-mgmt',
  'Advanced',
  '4 Weeks',
  'Advanced',
  'Dabur AYUSH Healthcare & Research Foundation',
  'Longitudinal Clinical Outcome Assessment of 3 Chronic Metabolic Cases',
  '[{"title": "Integrative Protocols for Non-Communicable Diseases", "url": "https://ayush.gov.in", "type": "document"}]'::jsonb,
  true
),
(
  'int-gmp-schedulet-course',
  'Schedule T GMP Compliance, In-Process QC & ASU Manufacturing',
  'Industrial certification course covering raw material authentication, microbial limits, heavy metal analysis, and Schedule T regulatory documentation for ASU drugs.',
  'Course',
  'comp-ayush-gmp-schedulet',
  'Applied',
  '3 Weeks',
  'Intermediate',
  'ASU Pharma Quality Cell & Dabur Research Foundation',
  'Batch Manufacturing Record (BMR) Audit and Heavy Metal Lab Report Review',
  '[{"title": "Drugs and Cosmetics Act Schedule T Overview", "url": "https://ayush.gov.in", "type": "document"}]'::jsonb,
  true
),
(
  'int-regulatory-filing-challenge',
  'AYUSH Export Dossier & Rule 158-B Regulatory Filing Simulation',
  'Hands-on regulatory challenge simulating filing of Form 24-D licenses, safety documentation for proprietary ASU formulations, and WHO-GMP export certificates.',
  'Research Challenge',
  'comp-ayush-regulatory-filing',
  'Advanced',
  '2 Weeks',
  'Advanced',
  'AYUSH Regulatory Council & Industry Cell',
  'Complete Technical Dossier for Herbal Formulation License Approval',
  '[{"title": "Ayurvedic Pharmacopoeia of India Formulations", "url": "https://pcimconline.nic.in", "type": "document"}]'::jsonb,
  true
),
(
  'int-yoga-chikitsa-workshop',
  'Therapeutic Yoga Protocol Prescription for Musculoskeletal & Metabolic Disorders',
  'Intensive workshop detailing biomechanical adaptations, Shatkriyas, and Pranayama sequences customized for spondylosis, hypertension, and stress-induced disorders.',
  'Workshop',
  'comp-ayush-yoga-chikitsa',
  'Applied',
  '1 Week (20 Hours)',
  'Intermediate',
  'Morarji Desai National Institute of Yoga (MDNIY)',
  'Individualized Therapeutic Yoga Session Plan with Contraindications',
  '[{"title": "WHO Benchmarks for Training in Yoga", "url": "https://www.who.int", "type": "document"}]'::jsonb,
  true
),
(
  'int-stress-autonomic-task',
  'Heart Rate Variability (HRV) & Autonomic Biofeedback Modulation',
  'Laboratory workstation testing autonomic nervous system tone modulation via Yoga Nidra and slow Pranayama using ECG-derived HRV metrics.',
  'Practical Task',
  'comp-ayush-stress-autonomic-regulation',
  'Applied',
  '10 Days',
  'Intermediate',
  'MDNIY Autonomic Research Laboratory',
  'Pre/Post Biofeedback HRV Modulation Dataset Analysis and Clinical Summary',
  '[{"title": "Autonomic Nervous System & Yogic Breathing Literature", "url": "https://pubmed.ncbi.nlm.nih.gov", "type": "document"}]'::jsonb,
  true
),
(
  'int-biostat-epidem-course',
  'Biostatistics & Epidemiological Sampling for AYUSH Clinical Trials',
  'Applied biostatistics curriculum covering power calculation, survival analysis, intention-to-treat (ITT) protocol, and statistical reporting in traditional medicine journals.',
  'Course',
  'comp-ayush-biostat-epidemiology',
  'Applied',
  '2 Weeks',
  'Intermediate',
  'Indian Institute of Public Health & CCRAS',
  'Sample Size Calculation & Statistical Analysis Plan (SAP) for AYUSH Trial',
  '[{"title": "CONSORT Extension for Herbal Medicine", "url": "https://www.consort-statement.org", "type": "document"}]'::jsonb,
  true
),
(
  'int-phytopharma-project',
  'Ayurvedic Phytopharmacology & Herb-Drug Interaction Matrix',
  'Laboratory project analyzing bioactive markers, fingerprinting (HPTLC/HPLC), and cytochrome P450 inhibition profiles of classical compound formulations.',
  'Industry Project',
  'comp-ayush-phytopharmacology',
  'Applied',
  '3 Weeks',
  'Intermediate',
  'Dabur R&D Phytochemistry Division',
  'HPTLC Fingerprinting Interpretation & CYP3A4 Interaction Assessment',
  '[{"title": "Ayurvedic Pharmacopoeia Quality Standards", "url": "https://pcimconline.nic.in", "type": "document"}]'::jsonb,
  true
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  type = EXCLUDED.type,
  competency_id = EXCLUDED.competency_id,
  target_maturity = EXCLUDED.target_maturity,
  estimated_duration = EXCLUDED.estimated_duration,
  difficulty = EXCLUDED.difficulty,
  provider = EXCLUDED.provider,
  evidence_required = EXCLUDED.evidence_required,
  supporting_resources = EXCLUDED.supporting_resources,
  active = EXCLUDED.active,
  updated_at = now();
